name: taskmanager
description: A simple Task Manager app with dark theme.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_messaging: ^14.7.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  get: ^4.6.5
  flutter_local_notifications: ^19.1.
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
